FROM golang:1.21.5 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./outbox

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/outbox /app/outbox
COPY --from=builder /app/data /app/data
COPY --from=builder /app/main /app/main

CMD ["./main"]