kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gokube
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 31000
    hostPort: 31000
  labels:
    tier: application
- role: worker
  labels:
    tier: broker