apiVersion: apps/v1
kind: Deployment
metadata:
  name: gokube-consumer
  labels:
    io.kompose.service: gokube-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gokube-consumer
  template:
    metadata:
      labels:
        io.kompose.service: gokube-consumer
    spec:
      nodeSelector:
        tier: application
      containers:
        - name: gokube-consumer
          image: lkumbrella/gokube-consumer:latest
          imagePullPolicy: Always
          env:
            - name: CRON
              value: '*/1 * * * * *'
            - name: KAFKA_ADDRESSES
              value: gokube-cluster-kafka-brokers.kafka:9092
            - name: LOGLEVEL
              value: debug
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: example-mongodb-admin-my-user
                  key: connectionString.standardSrv
            - name: MONGO_DATABASE
              value: gokube
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/health
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 10
          ports:
            - name: gokube-consumer
              containerPort: 8080
          resources: 
            requests:
              memory: "64Mi"
            limits:
              memory: "128Mi"
              cpu: "250m"
