apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gokube-outbox
  name: gokube-outbox
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: gokube-outbox
  template:
    metadata:
      labels:
        io.kompose.network/gokube-default: "true"
        io.kompose.service: gokube-outbox
    spec:
      nodeSelector:
        tier: application
      containers:
        - name: gokube-outbox
          image: lkumbrella/gokube-outbox:latest
          env:
            - name: CRON
              value: '*/1 * * * * *'
            - name: KAFKA_ADDRESSES
              value: kafka:9093
            - name: LOGLEVEL
              value: information
            - name: MONGO_CONNECTION_STRING
              value: my-user:gokube-password@example-mongodb-0.example-mongodb-svc.default.svc.cluster.local:27017,example-mongodb-1.example-mongodb-svc.default.svc.cluster.local:27017,example-mongodb-2.example-mongodb-svc.default.svc.cluster.local:27017/admin?replicaSet=example-mongodb&ssl=false
            - name: MONGO_DATABASE
              value: gokube
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/health
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 3
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              hostPort: 8090
          resources: 
            requests:
              memory: "64Mi"
            limits:
              memory: "128Mi"
              cpu: "250m"
