apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    io.kompose.service: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  template:
    metadata:
      labels:
        io.kompose.network/gokube-default: "true"
        io.kompose.service: kafka
    spec:
      nodeSelector:
        tier: broker
      enableServiceLinks: false #https://github.com/confluentinc/schema-registry/issues/689#issuecomment-824769666
      containers:
        - name: gokube-kafka
          image: confluentinc/cp-kafka:7.5.3
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:29092,GOKUBE_LOCAL://localhost:9092,GOKUBE_CONTAINERS://kafka:9093
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,GOKUBE_LOCAL:PLAINTEXT,GOKUBE_CONTAINERS:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          ports:
            - containerPort: 9092
            - containerPort: 9093
          resources: 
            requests:
              memory: "64Mi"
            limits:
              memory: "128Mi"
              cpu: "250m"
