apiVersion: v1
kind: Service
metadata:
  name: gokube-kafka
  labels:
    io.kompose.service: kafka
spec:
  selector:
    io.kompose.service: kafka
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9093"
      port: 9093
      targetPort: 9093
