apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-local
  labels:
    io.kompose.service: mongo-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi