apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    io.kompose.service: mongodb
spec:
  type: NodePort
  selector:
    io.kompose.service: mongodb
  ports:
    - port: 30000
      nodePort: 30000
      targetPort: 27017
