apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    io.kompose.service: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/gokube-default: "true"
        io.kompose.service: mongodb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: NotIn
                    values:
                    - application
                    - broker
      containers:
        - image: mongo:7.0.4
          name: mongo
          args:
            - mongod
            - --replSet
            - rs0
            - --quiet
            - --bind_ip_all
            - --logpath
            - /dev/null
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - db.runCommand('ping').ok
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 1
            timeoutSeconds: 10
          ports:
            - containerPort: 27017
          resources: 
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-local
      volumes:
        - name: mongo-local
          persistentVolumeClaim:
            claimName: mongo-local

